name = "CobblemonInnis"
author = "Innis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb3cada760d94c83bd99ac37bfd40352e64c08d84d4c82675b01854ea43b17cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"
